<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Admin\Review;
use App\Models\Admin\Teacher;
use Faker\Generator as Faker;

// library to use Laravel Helper
use Illuminate\Support\Str; 

class ReviewSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run(Faker $faker)
    {
        $teachers = Teacher::all();

        for ($i = 0; $i < 200; $i++) {
            $newReview = new Review();
            $newReview->teacher_id = $faker->numberBetween(1, count($teachers));
            $newReview->description = $faker->randomElement([
                'Ottimo insegnante, chiaro e preparato. Consigliatissimo!',
                'Competente e disponibile. Le sue lezioni sono interessanti.',
                'Non mi è piaciuto il suo approccio didattico.',
                'Bravo nel coinvolgere gli studenti, ma le valutazioni sono troppo severe.',
                'Molto bravo a spiegare argomenti complessi in modo semplice.',
                'Professore molto disponibile e gentile. Mi ha aiutato a comprendere meglio gli argomenti.',
                'Le sue lezioni sono noiose e poco interattive.',
                'Insegnante molto preparato e appassionato.',
                'Non lo consiglierei. Scarso metodo didattico.',
                'Molto chiaro nelle spiegazioni e sempre disponibile a chiarire i dubbi.',
                'Insegnante molto competente e preparato. Ha reso le lezioni stimolanti.',
                'Le sue lezioni sono sempre interessanti e coinvolgenti.',
                'Bravo nel coinvolgere gli studenti, ma troppo severo nelle valutazioni.',
                'Molto bravo nel trasmettere la passione per la materia.',
                'Non è riuscito a mantenermi interessato durante le lezioni.',
                'Insegnante preparato ma poco chiaro nelle spiegazioni.',
                'Mi ha aiutato tantissimo a superare l\'esame.',
                'Non lo consiglierei. Le lezioni sono disorganizzate.',
                'Ottimo professore, preparato e disponibile.',
                'Le sue spiegazioni sono sempre molto chiare.',
                'Insegnante competente e disponibile. Molto bravo nel coinvolgere gli studenti.',
                'Professore molto preparato ma poco disponibile al dialogo.',
                'Non mi sono trovato bene con lui. Le lezioni sono state poco interessanti.',
                'Molto bravo nel spiegare concetti complessi in modo semplice e comprensibile.',
                'Insegnante preparato ma poco coinvolgente.',
                'Consigliatissimo. Ha reso la materia interessante e comprensibile.',
                'Le lezioni sono state molto utili e interessanti.',
                'Insegnante preparato ma poco disponibile a chiarire i dubbi.',
                'Non lo consiglierei. Le lezioni sono noiose e poco interattive.',
                'Molto preparato e disponibile. Ha reso le lezioni stimolanti.',
                'Insegnante molto competente e preparato. Sempre disponibile a chiarire i dubbi.',
                'Le sue lezioni sono sempre chiare e interessanti.',
                'Bravo nel coinvolgere gli studenti, ma troppo severo nelle valutazioni.',
                'Molto bravo nel trasmettere la passione per la materia.',
                'Non è riuscito a mantenermi interessato durante le lezioni.',
                'Insegnante preparato ma poco chiaro nelle spiegazioni.',
                'Mi ha aiutato tantissimo a superare l\'esame.',
                'Non lo consiglierei. Le lezioni sono disorganizzate.',
                'Ottimo professore, preparato e disponibile.',
                'Le sue spiegazioni sono sempre molto chiare.',
                'Insegnante competente e disponibile. Molto bravo nel coinvolgere gli studenti.',
                'Professore molto preparato ma poco disponibile al dialogo.',
                'Non mi sono trovato bene con lui. Le lezioni sono state poco interessanti.',
                'Molto bravo nel spiegare concetti complessi in modo semplice e comprensibile.',
                'Insegnante preparato ma poco coinvolgente.',
                'Consigliatissimo. Ha reso la materia interessante e comprensibile.',
                'Le lezioni sono state molto utili e interessanti.',
                'Insegnante preparato ma poco disponibile a chiarire i dubbi.',
                'Non lo consiglierei. Le lezioni sono noiose e poco interattive.',
                'Molto preparato e disponibile. Ha reso le lezioni stimolanti.',
                'Insegnante molto competente e preparato. Sempre disponibile a chiarire i dubbi.',
                'Le sue lezioni sono sempre chiare e interessanti.',
                'Bravo nel coinvolgere gli studenti, ma troppo severo nelle valutazioni.',
                'Molto bravo nel trasmettere la passione per la materia.',
                'Non è riuscito a mantenermi interessato durante le lezioni.',
                'Insegnante preparato ma poco chiaro nelle spiegazioni.',
                'Mi ha aiutato tantissimo a superare l\'esame.',
                'Non lo consiglierei. Le lezioni sono disorganizzate.',
                'Ottimo professore, preparato e disponibile.',
                'Le sue spiegazioni sono sempre molto chiare.',
                'Insegnante competente e disponibile. Molto bravo nel coinvolgere gli studenti.',
                'Professore molto preparato ma poco disponibile al dialogo.',
                'Non mi sono trovato bene con lui. Le lezioni sono state poco interessanti.',
                'Molto bravo nel spiegare concetti complessi in modo semplice e comprensibile.',
                'Insegnante preparato ma poco coinvolgente.',
                'Consigliatissimo. Ha reso la materia interessante e comprensibile.',
                'Le lezioni sono state molto utili e interessanti.',
                'Insegnante preparato ma poco disponibile a chiarire i dubbi.',
                'Non lo consiglierei. Le lezioni sono noiose e poco interattive.',
                'Molto preparato e disponibile. Ha reso le lezioni stimolanti.',
                'Insegnante molto competente e preparato. Sempre disponibile a chiarire i dubbi.',
                'Le sue lezioni sono sempre chiare e interessanti.',
                'Bravo nel coinvolgere gli studenti, ma troppo severo nelle valutazioni.',
                'Molto bravo nel trasmettere la passione per la materia.',
                'Non è riuscito a mantenermi interessato durante le lezioni.',
                'Insegnante preparato ma poco chiaro nelle spiegazioni.',
                'Mi ha aiutato tantissimo a superare l\'esame.',
                'Non lo consiglierei. Le lezioni sono disorganizzate.',
                'Ottimo professore, preparato e disponibile.',
                'Le sue spiegazioni sono sempre molto chiare.',
                'Insegnante competente e disponibile. Molto bravo nel coinvolgere gli studenti.',
                'Professore molto preparato ma poco disponibile al dialogo.',
                'Non mi sono trovato bene con lui. Le lezioni sono state poco interessanti.',
                'Molto bravo nel spiegare concetti complessi in modo semplice e comprensibile.',
                'Insegnante preparato ma poco coinvolgente.',
                'Consigliatissimo. Ha reso la materia interessante e comprensibile.',
                'Le lezioni sono state molto utili e interessanti.',
                'Insegnante preparato ma poco disponibile a chiarire i dubbi.',
                'Non lo consiglierei. Le lezioni sono noiose e poco interattive.',
                'Molto preparato e disponibile. Ha reso le lezioni stimolanti.',
                'Insegnante molto competente e preparato. Sempre disponibile a chiarire i dubbi.',
                'Le sue lezioni sono sempre chiare e interessanti.',
                'Bravo nel coinvolgere gli studenti, ma troppo severo nelle valutazioni.',
                'Molto bravo nel trasmettere la passione per la materia.',
                'Non è riuscito a mantenermi interessato durante le lezioni.',
                'Insegnante preparato ma poco chiaro nelle spiegazioni.',
                'Mi ha aiutato tantissimo a superare l\'esame.',
                'Non lo consiglierei. Le lezioni sono disorganizzate.',
                'Ottimo professore, preparato e disponibile.',
                'Le sue spiegazioni sono sempre molto chiare.',
                'Insegnante competente e disponibile. Molto bravo nel coinvolgere gli studenti.',
                'Professore molto preparato ma poco disponibile al dialogo.',
                'Non mi sono trovato bene con lui. Le lezioni sono state poco interessanti.',
                'Molto bravo nel spiegare concetti complessi in modo semplice e comprensibile.',
                'Insegnante preparato ma poco coinvolgente.',
                'Consigliatissimo. Ha reso la materia interessante e comprensibile.',
                'Le lezioni sono state molto utili e interessanti.',
                'Insegnante preparato ma poco disponibile a chiarire i dubbi.',
                'Non lo consiglierei. Le lezioni sono noiose e poco interattive.',
                'Molto preparato e disponibile. Ha reso le lezioni stimolanti.',
                'Insegnante molto competente e preparato. Sempre disponibile a chiarire i dubbi.',
                'Le sue lezioni sono sempre chiare e interessanti.',
                'Bravo nel coinvolgere gli studenti, ma troppo severo nelle valutazioni.',
                'Molto bravo nel trasmettere la passione per la materia.',
                'Non è riuscito a mantenermi interessato durante le lezioni.',
                'Insegnante preparato ma poco chiaro nelle spiegazioni.',
                'Mi ha aiutato tantissimo a superare l\'esame.',
                'Non lo consiglierei. Le lezioni sono disorganizzate.',
                'Ottimo professore, preparato e disponibile.',
                'Le sue spiegazioni sono sempre molto chiare.',
                'Insegnante competente e disponibile. Molto bravo nel coinvolgere gli studenti.',
                'Professore molto preparato ma poco disponibile al dialogo.',
                'Non mi sono trovato bene con lui. Le lezioni sono state poco interessanti.',
                'Molto bravo nel spiegare concetti complessi in modo semplice e comprensibile.',
                'Insegnante preparato ma poco coinvolgente.',
                'Consigliatissimo. Ha reso la materia interessante e comprensibile.',
                'Le lezioni sono state molto utili e interessanti.',
                'Insegnante preparato ma poco disponibile a chiarire i dubbi.',
                'Non lo consiglierei. Le lezioni sono noiose e poco interattive.',
                'Molto preparato e disponibile. Ha reso le lezioni stimolanti.',
                'Insegnante molto competente e preparato. Sempre disponibile a chiarire i dubbi.',
                'Le sue lezioni sono sempre chiare e interessanti.',
                'Bravo nel coinvolgere gli studenti, ma troppo severo nelle valutazioni.',
                'Molto bravo nel trasmettere la passione per la materia.',
                'Non è riuscito a mantenermi interessato durante le lezioni.',
                'Insegnante preparato ma poco chiaro nelle spiegazioni.',
                'Mi ha aiutato tantissimo a superare l\'esame.',
                'Non lo consiglierei. Le lezioni sono disorganizzate.',
                'Ottimo professore, preparato e disponibile.',
                'Le sue spiegazioni sono sempre molto chiare.',
                'Insegnante competente e disponibile. Molto bravo nel coinvolgere gli studenti.',
                'Professore molto preparato ma poco disponibile al dialogo.',
                'Non mi sono trovato bene con lui. Le lezioni sono state poco interessanti.',
                'Molto bravo nel spiegare concetti complessi in modo semplice e comprensibile.',
                'Insegnante preparato ma poco coinvolgente.',
                'Consigliatissimo. Ha reso la materia interessante e comprensibile.',
                'Le lezioni sono state molto utili e interessanti.',
                'Insegnante preparato ma poco disponibile a chiarire i dubbi.',
                'Non lo consiglierei. Le lezioni sono noiose e poco interattive.',
                'Molto preparato e disponibile. Ha reso le lezioni stimolanti.',
                'Insegnante molto competente e preparato. Sempre disponibile a chiarire i dubbi.',
                'Le sue lezioni sono sempre chiare e interessanti.',
                'Bravo nel coinvolgere gli studenti, ma troppo severo nelle valutazioni.',
                'Molto bravo nel trasmettere la passione per la materia.',
                'Non è riuscito a mantenermi interessato durante le lezioni.',
                'Insegnante preparato ma poco chiaro nelle spiegazioni.',
                'Mi ha aiutato tantissimo a superare l\'esame.',
                'Non lo consiglierei. Le lezioni sono disorganizzate.',
                'Ottimo professore, preparato e disponibile.',
                'Le sue spiegazioni sono sempre molto chiare.',
                'Insegnante competente e disponibile. Molto bravo nel coinvolgere gli studenti.',
                'Professore molto preparato ma poco disponibile al dialogo.',
                'Non mi sono trovato bene con lui. Le lezioni sono state poco interessanti.',
                'Molto bravo nel spiegare concetti complessi in modo semplice e comprensibile.',
                'Insegnante preparato ma poco coinvolgente.',
                'Consigliatissimo. Ha reso la materia interessante e comprensibile.',
                'Le lezioni sono state molto utili e interessanti.',
                'Insegnante preparato ma poco disponibile a chiarire i dubbi.',
                'Non lo consiglierei. Le lezioni sono noiose e poco interattive.',
                'Molto preparato e disponibile. Ha reso le lezioni stimolanti.',
                'Insegnante molto competente e preparato. Sempre disponibile a chiarire i dubbi.',
                'Le sue lezioni sono sempre chiare e interessanti.',
                'Bravo nel coinvolgere gli studenti, ma troppo severo nelle valutazioni.',
                'Molto bravo nel trasmettere la passione per la materia.',
                'Non è riuscito a mantenermi interessato durante le lezioni.',
                'Insegnante preparato ma poco chiaro nelle spiegazioni.',
                'Mi ha aiutato tantissimo a superare l\'esame.',
                'Non lo consiglierei. Le lezioni sono disorganizzate.',
                'Ottimo professore, preparato e disponibile.',
                'Le sue spiegazioni sono sempre molto chiare.',
                'Insegnante competente e disponibile. Molto bravo nel coinvolgere gli studenti.',
                'Professore molto preparato ma poco disponibile al dialogo.',
                'Non mi sono trovato bene con lui. Le lezioni sono state poco interessanti.',
                'Molto bravo nel spiegare concetti complessi in modo semplice e comprensibile.',
                'Insegnante preparato ma poco coinvolgente.',
                'Consigliatissimo. Ha reso la materia interessante e comprensibile.',
                'Le lezioni sono state molto utili e interessanti.',
                'Insegnante preparato ma poco disponibile a chiarire i dubbi.',
                'Non lo consiglierei. Le lezioni sono noiose e poco interattive.',
                'Molto preparato e disponibile. Ha reso le lezioni stimolanti.',
                'Insegnante molto competente e preparato. Sempre disponibile a chiarire i dubbi.',
                'Le sue lezioni sono sempre chiare e interessanti.',
                'Bravo nel coinvolgere gli studenti, ma troppo severo nelle valutazioni.',
                'Molto bravo nel trasmettere la passione per la materia.',
                'Non è riuscito a mantenermi interessato durante le lezioni.',
                'Insegnante preparato ma poco chiaro nelle spiegazioni.',
                'Mi ha aiutato tantissimo a superare l\'esame.',
                'Non lo consiglierei. Le lezioni sono disorganizzate.',
                'Ottimo professore, preparato e disponibile.',
                'Le sue spiegazioni sono sempre molto chiare.',
                'Insegnante competente e disponibile. Molto bravo nel coinvolgere gli studenti.',
                'Professore molto preparato ma poco disponibile al dialogo.',
                'Non mi sono trovato bene con lui. Le lezioni sono state poco interessanti.',
                'Molto bravo nel spiegare concetti complessi in modo semplice e comprensibile.',
                'Insegnante preparato ma poco coinvolgente.',
                'Consigliatissimo. Ha reso la materia interessante e comprensibile.',
                'Le lezioni sono state molto utili e interessanti.',
                'Insegnante preparato ma poco disponibile a chiarire i dubbi.',
                'Non lo consiglierei. Le lezioni sono noiose e poco interattive.',
                'Molto preparato e disponibile. Ha reso le lezioni stimolanti.',
                'Insegnante molto competente e preparato. Sempre disponibile a chiarire i dubbi.',
                'Le sue lezioni sono sempre chiare e interessanti.',
                'Bravo nel coinvolgere gli studenti, ma troppo severo nelle valutazioni.',
                'Molto bravo nel trasmettere la passione per la materia.',
                'Non è riuscito a mantenermi interessato durante le lezioni.',
                'Insegnante preparato ma poco chiaro nelle spiegazioni.',
                'Mi ha aiutato tantissimo a superare l\'esame.',
                'Non lo consiglierei. Le lezioni sono disorganizzate.',
                'Ottimo professore, preparato e disponibile.',
                'Le sue spiegazioni sono sempre molto chiare.',
                'Insegnante competente e disponibile. Molto bravo nel coinvolgere gli studenti.',
                'Professore molto preparato ma poco disponibile al dialogo.',
                'Non mi sono trovato bene con lui. Le lezioni sono state poco interessanti.',
                'Molto bravo nel spiegare concetti complessi in modo semplice e comprensibile.',
                'Insegnante preparato ma poco coinvolgente.',
                'Consigliatissimo. Ha reso la materia interessante e comprensibile.',
                'Le lezioni sono state molto utili e interessanti.',
                'Insegnante preparato ma poco disponibile a chiarire i dubbi.',
                'Non lo consiglierei. Le lezioni sono noiose e poco interattive.',
                'Molto preparato e disponibile. Ha reso le lezioni stimolanti.',
                'Insegnante molto competente e preparato. Sempre disponibile a chiarire i dubbi.',
                'Le sue lezioni sono sempre chiare e interessanti.',
                'Bravo nel coinvolgere gli studenti, ma troppo severo nelle valutazioni.',
                'Molto bravo nel trasmettere la passione per la materia.',
                'Non è riuscito a mantenermi interessato durante le lezioni.',
                'Insegnante preparato ma poco chiaro nelle spiegazioni.',
                'Mi ha aiutato tantissimo a superare l\'esame.',
                'Non lo consiglierei. Le lezioni sono disorganizzate.',
                'Ottimo professore, preparato e disponibile.',
                'Le sue spiegazioni sono sempre molto chiare.',
                'Insegnante competente e disponibile. Molto bravo nel coinvolgere gli studenti.',
                'Professore molto preparato ma poco disponibile al dialogo.',
                'Non mi sono trovato bene con lui. Le lezioni sono state poco interessanti.',
                'Molto bravo nel spiegare concetti complessi in modo semplice e comprensibile.',
                'Insegnante preparato ma poco coinvolgente.',
                'Consigliatissimo. Ha reso la materia interessante e comprensibile.',
                'Le lezioni sono state molto utili e interessanti.',
                'Insegnante preparato ma poco disponibile a chiarire i dubbi.',
                'Non lo consiglierei. Le lezioni sono noiose e poco interattive.',
                'Molto preparato e disponibile. Ha reso le lezioni stimolanti.',
                'Insegnante molto competente e preparato. Sempre disponibile a chiarire i dubbi.',
                'Le sue lezioni sono sempre chiare e interessanti.',
                'Bravo nel coinvolgere gli studenti, ma troppo severo nelle valutazioni.',
                'Molto bravo nel trasmettere la passione per la materia.',
                'Non è riuscito a mantenermi interessato durante le lezioni.',
                'Insegnante preparato ma poco chiaro nelle spiegazioni.',
                'Mi ha aiutato tantissimo a superare l\'esame.',
                'Non lo consiglierei. Le lezioni sono disorganizzate.',
                'Ottimo professore, preparato e disponibile.',
                'Le sue spiegazioni sono sempre molto chiare.',
                'Insegnante competente e disponibile. Molto bravo nel coinvolgere gli studenti.',
                'Professore molto preparato ma poco disponibile al dialogo.',
                'Non mi sono trovato bene con lui. Le lezioni sono state poco interessanti.',
                'Molto bravo nel spiegare concetti complessi in modo semplice e comprensibile.',
                'Insegnante preparato ma poco coinvolgente.',
                'Consigliatissimo. Ha reso la materia interessante e comprensibile.',
                'Le lezioni sono state molto utili e interessanti.',
                'Insegnante preparato ma poco disponibile a chiarire i dubbi.',
                'Non lo consiglierei. Le lezioni sono noiose e poco interattive.',
                'Molto preparato e disponibile. Ha reso le lezioni stimolanti.',
                'Insegnante molto competente e preparato. Sempre disponibile a chiarire i dubbi.',
                'Le sue lezioni sono sempre chiare e interessanti.',
                'Bravo nel coinvolgere gli studenti, ma troppo severo nelle valutazioni.',
                'Molto bravo nel trasmettere la passione per la materia.',
                'Non è riuscito a mantenermi interessato durante le lezioni.',
                'Insegnante preparato ma poco chiaro nelle spiegazioni.',
                'Mi ha aiutato tantissimo a superare l\'esame.',
                'Non lo consiglierei. Le lezioni sono disorganizzate.',
                'Ottimo professore, preparato e disponibile.',
                'Le sue spiegazioni sono sempre molto chiare.',
                'Insegnante competente e disponibile. Molto bravo nel coinvolgere gli studenti.',
                'Professore molto preparato ma poco disponibile al dialogo.',
                'Non mi sono trovato bene con lui. Le lezioni sono state poco interessanti.',
                'Molto bravo nel spiegare concetti complessi in modo semplice e comprensibile.',
                'Insegnante preparato ma poco coinvolgente.',
                'Consigliatissimo. Ha reso la materia interessante e comprensibile.',
                'Le lezioni sono state molto utili e interessanti.',
                'Insegnante preparato ma poco disponibile a chiarire i dubbi.',
                'Non lo consiglierei. Le lezioni sono noiose e poco interattive.',
                'Molto preparato e disponibile. Ha reso le lezioni stimolanti.',
                'Insegnante molto competente e preparato. Sempre disponibile a chiarire i dubbi.',
                'Le sue lezioni sono sempre chiare e interessanti.',
                'Bravo nel coinvolgere gli studenti, ma troppo severo nelle valutazioni.',
                'Molto bravo nel trasmettere la passione per la materia.',
                'Non è riuscito a mantenermi interessato durante le lezioni.',
                'Insegnante preparato ma poco chiaro nelle spiegazioni.',
                'Mi ha aiutato tantissimo a superare l\'esame.',
                'Non lo consiglierei. Le lezioni sono disorganizzate.',
                'Ottimo professore, preparato e disponibile.',
                'Le sue spiegazioni sono sempre molto chiare.',
                'Insegnante competente e disponibile. Molto bravo nel coinvolgere gli studenti.',
                'Professore molto preparato ma poco disponibile al dialogo.',
                'Non mi sono trovato bene con lui. Le lezioni sono state poco interessanti.',
                'Molto bravo nel spiegare concetti complessi in modo semplice e comprensibile.',
                'Insegnante preparato ma poco coinvolgente.',
                'Consigliatissimo. Ha reso la materia interessante e comprensibile.',
                'Le lezioni sono state molto utili e interessanti.',
                'Insegnante preparato ma poco disponibile a chiarire i dubbi.',
                'Non lo consiglierei. Le lezioni sono noiose e poco interattive.',
                'Molto preparato e disponibile. Ha reso le lezioni stimolanti.',
                'Insegnante molto competente e preparato. Sempre disponibile a chiarire i dubbi.',
                'Le sue lezioni sono sempre chiare e interessanti.',
                'Bravo nel coinvolgere gli studenti, ma troppo severo nelle valutazioni.',
                'Molto bravo nel trasmettere la passione per la materia.',
                'Non è riuscito a mantenermi interessato durante le lezioni.',
                'Insegnante preparato ma poco chiaro nelle spiegazioni.',
                'Mi ha aiutato tantissimo a superare l\'esame.',
                'Non lo consiglierei. Le lezioni sono disorganizzate.',
                'Ottimo professore, preparato e disponibile.',
                'Le sue spiegazioni sono sempre molto chiare.',
                'Insegnante competente e disponibile. Molto bravo nel coinvolgere gli studenti.',
                'Professore molto preparato ma poco disponibile al dialogo.',
                'Non mi sono trovato bene con lui. Le lezioni sono state poco interessanti.',
                'Molto bravo nel spiegare concetti complessi in modo semplice e comprensibile.',
                'Insegnante preparato ma poco coinvolgente.',
                'Consigliatissimo. Ha reso la materia interessante e comprensibile.',
                'Le lezioni sono state molto utili e interessanti.',
            ]);
            $newReview->rate = $faker->numberBetween(1, 5);
            $newReview->guest_name = $faker->name;
            $newReview->guest_email = $faker->email;
            $newReview->save();
        }
    }
}
